### ISSUE TITLE
Suitable for chinese？

### ISSUE THREAD

**Issue by Gavingx** [sberbank-ai/DetIE#1]
Hi，is this code can be used for chinese OpenIE？ Have you tried？

**Comment by alexeyev** [comment]
Dear colleague,
thank you for your interest in our work. 

Since multilingual BERT we have used as a foundation was trained on [texts in 104 languages including Chinese](https://github.com/google-research/bert/blob/master/multilingual.md#list-of-languages), transfer learning approach here might work to a certain extent.

However, we haven't carried out any experiments on Chinese data, so we can't be sure.
